<?php
/** @var \Magento\Framework\View\Element\BlockInterface $block */
$order = $block->getOrder();
$customDiscount = $order->getData('custom_discount');
?>

<style>
    .admin__table-secondary {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
        margin-top: 10px;
    }

    .order-totals {
        /*border: 1px solid #d6d6d6;*/
    }

    .order-totals th {
        text-align: left;
        padding: 12px;
        background-color: #f7f7f7;
        border-bottom: 1px solid #d6d6d6;
        font-weight: bold;
    }

    .order-totals td {
        padding: 12px;
        border-bottom: 1px solid #d6d6d6;
    }

    .order-totals .admin__label {
        width: 50%;
    }

    .order-totals .admin__value {
        width: 50%;
    }
    

</style>

<table class="data-table admin__table-secondary order-totals">
    <tbody>
    <tr>
        <td class="admin__label">
            <span><?= __('Custom Discount') ?></span>
        </td>
        <td class="admin__value">
            <?= ($customDiscount !== null && $customDiscount !== '') ? $order->formatPrice($customDiscount) : '$0.00' ?>
        </td>
    </tr>
    <tr>
        <td class="admin__label">
            <span><?= __('Grand Total') ?></span>
        </td>
        <td class="admin__value">
            <span class="price"><?= $order->formatPrice($order->getGrandTotal()) ?></span>
        </td>
    </tr>
    <tr>
        <td class="admin__label">
            <span><?= __('Total Paid') ?></span>
        </td>
        <td class="admin__value">
            <span class="price"><?= $order->formatPrice($order->getTotalPaid()) ?></span>
        </td>
    </tr>
    <tr>
        <td class="admin__label">
            <span><?= __('Total Refunded') ?></span>
        </td>
        <td class="admin__value">
            <span class="price"><?= $order->formatPrice($order->getTotalRefunded()) ?></span>
        </td>
    </tr>
    <tr>
        <td class="admin__label">
            <span><?= __('Total Due') ?></span>
        </td>
        <td class="admin__value">
            <span class="price"><?= $order->formatPrice($order->getTotalDue()) ?></span>
        </td>
    </tr>
    <tr>
        <td class="admin__label">
            <span><?= __('Subtotal') ?></span>
        </td>
        <td class="admin__value">
            <span class="price"><?= $order->formatPrice($order->getSubtotal()) ?></span>
        </td>
    </tr>
    <tr>
        <td class="admin__label">
            <span><?= __('Shipping & Handling') ?></span>
        </td>
        <td class="admin__value">
            <span class="price"><?= $order->formatPrice($order->getShippingAmount()) ?></span>
        </td>
    </tr>
    </tbody>
</table>
